[package]
name = "terminalgames"
version = "0.1.0"
authors = ["edoardo <edovi@icloud.com>"]
private = true

[dependencies]
pancurses = "0.16.0"
rand = "0.5.5"
uuid = {version="0.6.0", features=["v4"]}
log = "0.4"
fern = "0.5"
chrono = "0.4.6"


[[bin]]
name="main"
path="bin/main.rs"